/* ElectronArt — asistente de la web (F22.4)
 *
 * Un ayudante chico, abajo a la derecha, que contesta las preguntas que se
 * repiten antes y después de comprar: cómo se descarga, cómo se instala,
 * cuánto dura cada licencia, cómo se crea la cuenta, cómo se activa, qué pasa
 * si cambio de PC. Hoy esas preguntas llegan por correo de a una.
 *
 * ── Por qué NO habla con una IA ────────────────────────────────────────────
 *
 * Sería lo obvio y sería peor. Tres razones, en orden:
 *
 * 1. **Inventaría.** Un modelo suelto sobre un producto que cobra USD 299
 *    contesta con seguridad cosas que no son —«tenés 30 días de reembolso»,
 *    «hay recuperación de contraseña»— y eso no es un chatbot flojo, es una
 *    promesa comercial falsa. Acá cada respuesta está escrita a mano y
 *    verificada contra el código: los precios contra `backend/seed.py`, los
 *    14 días contra `DIAS_PRUEBA`, el reembolso contra la sección 9 del EULA.
 * 2. **El hosting no puede.** La cuenta gratuita de PythonAnywhere sólo deja
 *    salir a una lista blanca de sitios: el backend no puede llamar a la API
 *    de nadie. Y con el plan pago sería una clave viviendo en el servidor más
 *    un costo por mensaje que crece con las visitas.
 * 3. **No hace falta.** Son veintipico de preguntas conocidas. Lo que hay que
 *    resolver no es entender lenguaje libre: es entender *sinónimos* — que
 *    «no me anda la clave», «perdí la contraseña» y «como recupero mi cuenta»
 *    son lo mismo. Eso lo hace el puntaje por palabras de acá abajo, sin red,
 *    sin costo, sin latencia y sin filtrar a un tercero lo que la gente
 *    pregunta.
 *
 * Cuando no está seguro, **lo dice** y ofrece el foro y el correo. Un «no sé»
 * honesto vale más que una respuesta inventada.
 *
 * ── No molesto ─────────────────────────────────────────────────────────────
 *
 * Arranca cerrado y no se abre solo nunca. Es una pestaña chica que se puede
 * ocultar del todo, y esa decisión se recuerda. No pide correo, no rastrea, no
 * manda nada a ningún lado: todo pasa en el navegador.
 *
 * Los tres idiomas salen del mismo lugar que el resto de la web: el atributo
 * `lang` del documento, que `i18n.js` mantiene al día. Se observa con un
 * MutationObserver en vez de tocar el interior de `i18n.js`, así ninguno de
 * los dos archivos depende de los detalles del otro.
 */
(function () {
  "use strict";

  var CLAVE_OCULTO = "ea_asistente_oculto";
  var CORREO = "soporte@electroniklosungen.com.ar";
  var FORO = "https://electronart.pythonanywhere.com";

  /* ── Textos de la interfaz ──────────────────────────────────────────────
     El asistente se inyecta DESPUÉS de que `i18n.js` capturó la página, así
     que sus nodos no pasan por el diccionario: se traduce solo, acá. */
  var UI = {
    es: {
      abrir: "¿Dudas?", titulo: "Asistente", subtitulo: "Respuestas rápidas",
      saludo: "Preguntame lo que quieras sobre ElectronArt: descargarlo, " +
              "instalarlo, los planes, la cuenta o la licencia.",
      sugeridas: "Preguntas frecuentes",
      escribi: "Escribí tu pregunta…", enviar: "Preguntar",
      relacionadas: "También te puede servir",
      nada: "No tengo una respuesta escrita para eso, y prefiero decírtelo " +
            "antes que inventarte una. Preguntalo en el foro o escribinos: " +
            "te contesta una persona.",
      pie: "Respuestas escritas por el equipo, no generadas por una IA.",
      ocultar: "Ocultar el asistente", cerrar: "Cerrar",
      foro: "Ir al foro", correo: "Escribir por correo"
    },
    en: {
      abrir: "Questions?", titulo: "Assistant", subtitulo: "Quick answers",
      saludo: "Ask me anything about ElectronArt: downloading it, installing " +
              "it, the plans, your account or your licence.",
      sugeridas: "Frequently asked",
      escribi: "Type your question…", enviar: "Ask",
      relacionadas: "This may also help",
      nada: "I do not have a written answer for that, and I would rather say " +
            "so than make one up. Ask it on the forum or write to us: a " +
            "person will answer.",
      pie: "Answers written by the team, not generated by an AI.",
      ocultar: "Hide the assistant", cerrar: "Close",
      foro: "Go to the forum", correo: "Write us an email"
    },
    pt: {
      abrir: "Dúvidas?", titulo: "Assistente", subtitulo: "Respostas rápidas",
      saludo: "Pergunte o que quiser sobre o ElectronArt: como baixar, como " +
              "instalar, os planos, a conta ou a licença.",
      sugeridas: "Perguntas frequentes",
      escribi: "Escreva a sua pergunta…", enviar: "Perguntar",
      relacionadas: "Isto também pode ajudar",
      nada: "Não tenho uma resposta escrita para isso, e prefiro dizer isso a " +
            "inventar uma. Pergunte no fórum ou escreva para nós: uma pessoa " +
            "responde.",
      pie: "Respostas escritas pela equipe, não geradas por uma IA.",
      ocultar: "Ocultar o assistente", cerrar: "Fechar",
      foro: "Ir ao fórum", correo: "Escrever por e-mail"
    }
  };

  /* ── Base de conocimiento ────────────────────────────────────────────────
     Cada entrada: `q` la pregunta canónica (la que se muestra), `k` las
     palabras por las que se la encuentra y `r` la respuesta en HTML.
     TODO dato numérico de acá está verificado contra el repo; si cambia el
     precio, la duración de la prueba o la política de reembolso, cambia acá.
     `dest` marca las cuatro que se ofrecen como sugerencias iniciales. */
  var BASE = [
    { id: "descargar", dest: true,
      q: { es: "¿Dónde descargo ElectronArt?",
           en: "Where do I download ElectronArt?",
           pt: "Onde eu baixo o ElectronArt?" },
      k: { es: "descargar descarga bajar baja donde consigo obtener link enlace instalador exe zip",
           en: "download get where link installer exe zip",
           pt: "baixar download onde consigo obter link instalador exe zip" },
      r: { es: "En la <a href='descargas.html'>página de descargas</a>. Bajá el archivo que termina en <code>-setup.exe</code>: ese es el instalador. Al lado está el ZIP portable, por si preferís no instalar nada.",
           en: "On the <a href='descargas.html'>downloads page</a>. Get the file ending in <code>-setup.exe</code>: that is the installer. Next to it is the portable ZIP, in case you would rather not install anything.",
           pt: "Na <a href='descargas.html'>página de downloads</a>. Baixe o arquivo terminado em <code>-setup.exe</code>: esse é o instalador. Ao lado está o ZIP portátil, caso prefira não instalar nada." } },

    { id: "instalar", dest: true,
      q: { es: "¿Cómo lo instalo?", en: "How do I install it?",
           pt: "Como eu instalo?" },
      k: { es: "instalar instalacion instalo como se instala setup asistente carpeta administrador",
           en: "install installation setup wizard folder administrator",
           pt: "instalar instalacao setup assistente pasta administrador" },
      r: { es: "Doble clic en el <code>-setup.exe</code> y seguir el asistente. Deja el acceso en el menú Inicio, el desinstalador en «Aplicaciones instaladas» y hace que los archivos <code>.ea</code> se abran con ElectronArt. <b>No pide permisos de administrador.</b>",
           en: "Double-click the <code>-setup.exe</code> and follow the wizard. It leaves a Start menu shortcut, an uninstaller under “Installed apps”, and makes <code>.ea</code> files open with ElectronArt. <b>It does not ask for administrator rights.</b>",
           pt: "Dê dois cliques no <code>-setup.exe</code> e siga o assistente. Ele deixa o atalho no menu Iniciar, o desinstalador em “Aplicativos instalados” e faz os arquivos <code>.ea</code> abrirem com o ElectronArt. <b>Não pede permissões de administrador.</b>" } },

    { id: "smartscreen",
      q: { es: "Windows dice que protegió mi PC. ¿Es un virus?",
           en: "Windows says it protected my PC. Is it a virus?",
           pt: "O Windows diz que protegeu o meu PC. É um vírus?" },
      k: { es: "smartscreen advertencia aviso windows protegio pc virus antivirus bloquea peligroso editor desconocido",
           en: "smartscreen warning windows protected pc virus antivirus blocks dangerous unknown publisher",
           pt: "smartscreen aviso windows protegeu pc virus antivirus bloqueia perigoso editor desconhecido" },
      r: { es: "No es un virus. SmartScreen avisa así de todo programa nuevo que todavía no acumuló descargas, y ElectronArt no está firmado con un certificado (cuesta cientos de dólares al año). Para seguir: <b>Más información ▸ Ejecutar de todas formas</b>. La forma seria de comprobar que el archivo es el nuestro es el <b>SHA-256</b> publicado en la página de descargas: si coincide, nadie lo tocó.",
           en: "It is not a virus. SmartScreen shows that for every new program that has not built up downloads yet, and ElectronArt is not signed with a certificate (they cost hundreds of dollars a year). To continue: <b>More info ▸ Run anyway</b>. The serious way to check the file is ours is the <b>SHA-256</b> published on the downloads page: if it matches, nobody touched it.",
           pt: "Não é um vírus. O SmartScreen avisa assim sobre todo programa novo que ainda não acumulou downloads, e o ElectronArt não está assinado com um certificado (custam centenas de dólares por ano). Para continuar: <b>Mais informações ▸ Executar mesmo assim</b>. A forma séria de conferir que o arquivo é o nosso é o <b>SHA-256</b> publicado na página de downloads: se bater, ninguém o alterou." } },

    { id: "actualizar",
      q: { es: "¿Cómo actualizo a una versión nueva?",
           en: "How do I update to a new version?",
           pt: "Como atualizo para uma versão nova?" },
      k: { es: "actualizar actualizacion actualiza version nueva update upgrade novedad ultima",
           en: "update upgrade new version latest",
           pt: "atualizar atualizacao versao nova update ultima" },
      r: { es: "Bajás el instalador nuevo y lo corrés: reemplaza la copia anterior. <b>No hay que desinstalar nada</b> y tus preferencias, tu biblioteca y tu licencia quedan como están. El programa además te avisa solo cuando sale una versión, y podés buscarla a mano en <b>Ayuda ▸ Buscar actualizaciones…</b>",
           en: "Download the new installer and run it: it replaces the previous copy. <b>You do not need to uninstall anything</b> and your preferences, your library and your licence stay as they are. The program also tells you on its own when a version comes out, and you can check by hand from <b>Help ▸ Check for updates…</b>",
           pt: "Baixe o instalador novo e execute: ele substitui a cópia anterior. <b>Não é preciso desinstalar nada</b> e suas preferências, sua biblioteca e sua licença continuam como estão. O programa também avisa sozinho quando sai uma versão, e você pode procurar em <b>Ajuda ▸ Procurar atualizações…</b>" } },

    { id: "desinstalar",
      q: { es: "¿Cómo lo desinstalo? ¿Pierdo mis diseños?",
           en: "How do I uninstall it? Do I lose my designs?",
           pt: "Como desinstalo? Perco os meus projetos?" },
      k: { es: "desinstalar desinstalo desinstalacion quitar quito borrar borro sacar saco eliminar elimino pierdo mis diseños archivos compu",
           en: "uninstall remove delete lose my designs files",
           pt: "desinstalar desinstalo remover apagar excluir perco meus projetos arquivos" },
      r: { es: "Desde <b>Configuración ▸ Aplicaciones instaladas ▸ ElectronArt ▸ Desinstalar</b>. No perdés nada: tus diseños están donde vos los guardaste, y tu biblioteca, tus preferencias y tu licencia viven fuera de la carpeta del programa. Si lo volvés a instalar, está todo como lo dejaste.",
           en: "From <b>Settings ▸ Installed apps ▸ ElectronArt ▸ Uninstall</b>. You lose nothing: your designs are wherever you saved them, and your library, preferences and licence live outside the program folder. If you install it again, everything is as you left it.",
           pt: "Em <b>Configurações ▸ Aplicativos instalados ▸ ElectronArt ▸ Desinstalar</b>. Você não perde nada: seus projetos estão onde você os salvou, e sua biblioteca, preferências e licença ficam fora da pasta do programa. Se instalar de novo, está tudo como você deixou." } },

    { id: "requisitos",
      q: { es: "¿Qué necesita mi computadora?",
           en: "What does my computer need?",
           pt: "Do que o meu computador precisa?" },
      k: { es: "requisitos necesita ram memoria espacio disco placa video grafica opengl minimo corre corren anda andara funciona notebook laptop portatil vieja lenta",
           en: "requirements needs ram memory space disk graphics card opengl minimum will it run works laptop notebook old slow",
           pt: "requisitos precisa ram memoria espaco disco placa video grafica opengl minimo roda funciona notebook laptop portatil velha lenta" },
      r: { es: "Windows 10 u 11 de 64 bits, 4 GB de RAM (8 GB si vas a hacer placas grandes), unos 350 MB de disco y una gráfica con OpenGL 2.1 o superior para la vista 3D — cualquier integrada de la última década alcanza.",
           en: "Windows 10 or 11, 64-bit, 4 GB of RAM (8 GB for large boards), about 350 MB of disk and a GPU with OpenGL 2.1 or later for the 3D view — any integrated GPU from the last decade is enough.",
           pt: "Windows 10 ou 11 de 64 bits, 4 GB de RAM (8 GB para placas grandes), cerca de 350 MB de disco e uma placa com OpenGL 2.1 ou superior para a vista 3D — qualquer integrada da última década dá conta." } },

    { id: "sistemas",
      q: { es: "¿Corre en Linux o en Mac?", en: "Does it run on Linux or Mac?",
           pt: "Roda no Linux ou no Mac?" },
      k: { es: "linux mac macos ubuntu sistema operativo otros sistemas",
           en: "linux mac macos ubuntu operating system other systems",
           pt: "linux mac macos ubuntu sistema operacional outros sistemas" },
      r: { es: "El programa corre en Windows, Linux y macOS: está hecho en Python con Qt y no depende de nada propio de un sistema. Lo que hoy publicamos compilado es el <b>instalador de Windows 10 y 11</b>; en Linux y macOS se ejecuta desde el código, y el paquete para esos dos está en camino.",
           en: "The program runs on Windows, Linux and macOS: it is written in Python with Qt and does not depend on anything system-specific. What we publish compiled today is the <b>Windows 10 and 11 installer</b>; on Linux and macOS you run it from source, and the package for those two is on the way.",
           pt: "O programa roda em Windows, Linux e macOS: é feito em Python com Qt e não depende de nada específico de um sistema. O que publicamos compilado hoje é o <b>instalador do Windows 10 e 11</b>; em Linux e macOS você executa a partir do código, e o pacote para esses dois está a caminho." } },

    { id: "planes", dest: true,
      q: { es: "¿Cuánto sale? ¿Qué planes hay?",
           en: "How much is it? What plans are there?",
           pt: "Quanto custa? Que planos existem?" },
      k: { es: "precio precios cuanto sale cuesta vale planes plan comprar pagar gratuito pro industrial dolares suscripcion",
           en: "price pricing how much cost plans plan buy pay pro industrial dollars subscription",
           pt: "preco precos quanto custa vale planos plano comprar pagar gratuito pro industrial dolares assinatura" },
      r: { es: "Tres planes: <b>Student, gratis</b> (uso personal y educativo), <b>Pro, USD 79 al año</b> y <b>Industrial, USD 299 al año</b>. La diferencia está en las capas del PCB, las simulaciones avanzadas, las salidas de fabricación exigentes y el módulo eléctrico/PLC, que sólo trae Industrial. Todo en la <a href='https://electronart.pythonanywhere.com/store'>tienda</a>.",
           en: "Three plans: <b>Student, free</b> (personal and educational use), <b>Pro, USD 79 a year</b> and <b>Industrial, USD 299 a year</b>. The difference is in PCB layers, advanced simulation, demanding fabrication outputs and the electrical/PLC module, which only Industrial includes. All of it in the <a href='https://electronart.pythonanywhere.com/store'>store</a>.",
           pt: "Três planos: <b>Student, grátis</b> (uso pessoal e educacional), <b>Pro, USD 79 por ano</b> e <b>Industrial, USD 299 por ano</b>. A diferença está nas camadas do PCB, nas simulações avançadas, nas saídas de fabricação exigentes e no módulo elétrico/PLC, que só o Industrial inclui. Tudo na <a href='https://electronart.pythonanywhere.com/store'>loja</a>." } },

    { id: "duracion", dest: true,
      q: { es: "¿Cuánto dura cada licencia?",
           en: "How long does each licence last?",
           pt: "Quanto dura cada licença?" },
      k: { es: "cuanto dura duracion vence vencimiento caduca renovar renovacion anual año suscripcion mensual perpetua para siempre",
           en: "how long lasts duration expires expiry renew renewal annual year subscription monthly perpetual forever",
           pt: "quanto dura duracao vence vencimento caduca renovar renovacao anual ano assinatura mensal perpetua para sempre" },
      r: { es: "<b>Pro e Industrial duran 12 meses</b> y se renuevan cada año; podés cancelar cuando quieras desde tu cuenta. <b>Gratuita y Estudiante no vencen.</b> La prueba de Pro dura <b>14 días</b>. Ojo: lo que vence es la licencia, no el programa — lo que ya diseñaste sigue siendo tuyo y tus archivos se abren igual.",
           en: "<b>Pro and Industrial last 12 months</b> and renew every year; you can cancel whenever you like from your account. <b>Free and Student do not expire.</b> The Pro trial lasts <b>14 days</b>. Note: what expires is the licence, not the program — what you designed is still yours and your files still open.",
           pt: "<b>Pro e Industrial duram 12 meses</b> e se renovam a cada ano; você pode cancelar quando quiser na sua conta. <b>Gratuita e Estudante não vencem.</b> O teste do Pro dura <b>14 dias</b>. Atenção: o que vence é a licença, não o programa — o que você projetou continua sendo seu e seus arquivos abrem do mesmo jeito." } },

    { id: "prueba",
      q: { es: "¿Hay una prueba gratis?", en: "Is there a free trial?",
           pt: "Existe um teste grátis?" },
      k: { es: "prueba probar gratis demo trial testear sin tarjeta 14 dias evaluar",
           en: "trial try free demo test without card 14 days evaluate",
           pt: "teste testar gratis demo trial sem cartao 14 dias avaliar" },
      r: { es: "Sí: <b>14 días de Pro, sin tarjeta</b>. Se pide desde <a href='https://electronart.pythonanywhere.com/prueba'>la página de prueba</a> o desde el propio programa. Al vencer no se borra nada: la copia vuelve al plan gratuito.",
           en: "Yes: <b>14 days of Pro, no card</b>. Request it from <a href='https://electronart.pythonanywhere.com/prueba'>the trial page</a> or from the program itself. When it ends nothing is deleted: the copy goes back to the free plan.",
           pt: "Sim: <b>14 dias de Pro, sem cartão</b>. Peça na <a href='https://electronart.pythonanywhere.com/prueba'>página de teste</a> ou no próprio programa. Quando termina, nada é apagado: a cópia volta ao plano gratuito." } },

    { id: "cuenta",
      q: { es: "¿Cómo creo una cuenta?", en: "How do I create an account?",
           pt: "Como crio uma conta?" },
      k: { es: "crear cuenta registrarme registro registrar alta usuario sign up inscribirme",
           en: "create account register registration sign up new user",
           pt: "criar conta registrar registro cadastro cadastrar usuario" },
      r: { es: "En <a href='https://electronart.pythonanywhere.com/register'>Crear cuenta</a>: nombre, correo y contraseña, nada más. La cuenta sirve para la tienda y el foro. <b>El programa no la necesita</b>: se usa sin conexión y sin iniciar sesión.",
           en: "At <a href='https://electronart.pythonanywhere.com/register'>Create account</a>: name, email and password, nothing else. The account is for the store and the forum. <b>The program does not need it</b>: it runs offline and without signing in.",
           pt: "Em <a href='https://electronart.pythonanywhere.com/register'>Criar conta</a>: nome, e-mail e senha, nada mais. A conta serve para a loja e o fórum. <b>O programa não precisa dela</b>: funciona offline e sem fazer login." } },

    { id: "contrasena",
      q: { es: "Olvidé mi contraseña, ¿cómo la recupero?",
           en: "I forgot my password, how do I recover it?",
           pt: "Esqueci a minha senha, como recupero?" },
      k: { es: "contraseña clave password olvide perdi recuperar recupero restablecer reset no puedo entrar no me deja iniciar sesion login",
           en: "password forgot lost recover reset cannot log in sign in login",
           pt: "senha password esqueci perdi recuperar redefinir reset nao consigo entrar login" },
      r: { es: "Te lo digo derecho: <b>todavía no hay recuperación automática de contraseña</b>. Escribinos a <a href='mailto:" + CORREO + "'>" + CORREO + "</a> desde el correo de la cuenta y te la restablecemos a mano. Está en la lista de lo que falta. Aparte: si lo que querés es <b>activar tu licencia</b>, la cuenta no hace falta — se activa con el correo de la compra desde el programa.",
           en: "Straight up: <b>there is no automatic password recovery yet</b>. Write to <a href='mailto:" + CORREO + "'>" + CORREO + "</a> from the account's email address and we reset it by hand. It is on the list of what is missing. Also: if what you want is to <b>activate your licence</b>, you do not need the account — it activates with the purchase email, from the program.",
           pt: "Vou ser direto: <b>ainda não há recuperação automática de senha</b>. Escreva para <a href='mailto:" + CORREO + "'>" + CORREO + "</a> a partir do e-mail da conta e nós redefinimos manualmente. Está na lista do que falta. Além disso: se o que você quer é <b>ativar a sua licença</b>, a conta não é necessária — ela é ativada com o e-mail da compra, dentro do programa." } },

    { id: "activar", dest: true,
      q: { es: "Compré. ¿Cómo activo la licencia?",
           en: "I bought it. How do I activate my licence?",
           pt: "Comprei. Como ativo a licença?" },
      k: { es: "activar activacion licencia clave codigo compre pague como uso lo que compre desbloquear",
           en: "activate activation licence license key code bought paid unlock",
           pt: "ativar ativacao licenca chave codigo comprei paguei desbloquear" },
      r: { es: "Adentro del programa: <b>Ayuda ▸ Activar licencia…</b>, ponés el <b>mismo correo con el que compraste</b> y te llega un código de 6 dígitos para confirmar que sos vos. Listo — de ahí en adelante funciona sin conexión. No hay archivos que copiar ni claves largas que pegar.",
           en: "Inside the program: <b>Help ▸ Activate licence…</b>, enter the <b>same email you bought with</b> and a 6-digit code arrives to confirm it is you. Done — from then on it works offline. No files to copy and no long keys to paste.",
           pt: "Dentro do programa: <b>Ajuda ▸ Ativar licença…</b>, coloque o <b>mesmo e-mail com que comprou</b> e chega um código de 6 dígitos para confirmar que é você. Pronto — daí em diante funciona sem conexão. Não há arquivos para copiar nem chaves longas para colar." } },

    { id: "no-activa",
      q: { es: "Compré y no me la reconoce",
           en: "I bought it and it is not recognised",
           pt: "Comprei e não é reconhecida" },
      k: { es: "no me activa no funciona no reconoce no encuentra licencia no aparece pague y nada error 404 no llego el correo spam",
           en: "not activating does not work not recognised licence not found nothing happened email did not arrive spam",
           pt: "nao ativa nao funciona nao reconhece licenca nao encontrada nao chegou o e-mail spam" },
      r: { es: "Casi siempre es una de tres: (1) estás usando <b>otro correo</b> que el de la compra — tiene que ser exactamente el mismo; (2) el <b>código quedó en spam</b>; (3) el pago todavía figura como pendiente en la pasarela. Si ninguna es, abrí <b>Ayuda ▸ Diagnóstico…</b> en el programa, copiá el informe (no incluye tu licencia ni tu correo) y mandanoslo a <a href='mailto:" + CORREO + "'>" + CORREO + "</a>.",
           en: "It is almost always one of three: (1) you are using <b>a different email</b> than the purchase one — it has to be exactly the same; (2) the <b>code went to spam</b>; (3) the payment is still pending at the gateway. If it is none of those, open <b>Help ▸ Diagnostics…</b> in the program, copy the report (it does not include your licence or your email) and send it to <a href='mailto:" + CORREO + "'>" + CORREO + "</a>.",
           pt: "Quase sempre é uma de três: (1) você está usando <b>outro e-mail</b> e não o da compra — tem que ser exatamente o mesmo; (2) o <b>código foi para o spam</b>; (3) o pagamento ainda está pendente no gateway. Se não for nenhuma, abra <b>Ajuda ▸ Diagnóstico…</b> no programa, copie o relatório (não inclui a sua licença nem o seu e-mail) e mande para <a href='mailto:" + CORREO + "'>" + CORREO + "</a>." } },

    { id: "estudiante",
      q: { es: "¿Cómo consigo la licencia de estudiante?",
           en: "How do I get the student licence?",
           pt: "Como consigo a licença de estudante?" },
      k: { es: "estudiante student escuela universidad facultad academico comprobante certificado alumno gratis estudio",
           en: "student school university academic proof certificate free studying",
           pt: "estudante escola universidade academico comprovante certificado aluno gratis estudo" },
      r: { es: "Creás la cuenta y pedís la verificación desde tu perfil. Con un correo institucional suele salir sola; si no, subís un comprobante (constancia de alumno, libreta, certificado) y lo aprobamos a mano. Es gratis y no vence, para uso no comercial.",
           en: "Create the account and request verification from your profile. With an institutional email it usually goes through on its own; if not, you upload proof (enrolment letter, student card, certificate) and we approve it by hand. It is free and does not expire, for non-commercial use.",
           pt: "Crie a conta e peça a verificação no seu perfil. Com um e-mail institucional geralmente sai sozinho; se não, você envia um comprovante (declaração de matrícula, carteirinha, certificado) e aprovamos manualmente. É grátis e não vence, para uso não comercial." } },

    { id: "pago",
      q: { es: "¿Cómo puedo pagar?", en: "How can I pay?",
           pt: "Como posso pagar?" },
      k: { es: "pago pagar metodos tarjeta mercadopago gumroad stripe paypal transferencia pesos argentina factura",
           en: "payment pay methods card mercadopago gumroad stripe paypal transfer invoice",
           pt: "pagamento pagar metodos cartao mercadopago gumroad stripe paypal transferencia nota fiscal" },
      r: { es: "Tarjeta internacional por Gumroad/Stripe, y <b>MercadoPago</b> para Argentina y Latinoamérica. Los dos botones están en la <a href='https://electronart.pythonanywhere.com/store'>tienda</a>.",
           en: "International card through Gumroad/Stripe, and <b>MercadoPago</b> for Argentina and Latin America. Both buttons are in the <a href='https://electronart.pythonanywhere.com/store'>store</a>.",
           pt: "Cartão internacional via Gumroad/Stripe e <b>MercadoPago</b> para Argentina e América Latina. Os dois botões estão na <a href='https://electronart.pythonanywhere.com/store'>loja</a>." } },

    { id: "reembolso",
      q: { es: "¿Puedo pedir un reembolso?", en: "Can I ask for a refund?",
           pt: "Posso pedir reembolso?" },
      k: { es: "reembolso devolucion devolver plata dinero garantia arrepentimiento cancelar compra",
           en: "refund money back guarantee return cancel purchase",
           pt: "reembolso devolucao dinheiro garantia cancelar compra" },
      r: { es: "Sí: <b>14 días</b> desde la compra si el programa no funciona en tu equipo y no lo pudimos resolver. Si compraste por una plataforma (Gumroad), valen además sus condiciones. Está en la sección 9 de los <a href='terminos.html'>Términos</a>.",
           en: "Yes: <b>14 days</b> from purchase if the program does not work on your machine and we could not solve it. If you bought through a platform (Gumroad), its own terms also apply. It is in section 9 of the <a href='terminos.html'>Terms</a>.",
           pt: "Sim: <b>14 dias</b> a partir da compra se o programa não funcionar na sua máquina e não conseguirmos resolver. Se você comprou por uma plataforma (Gumroad), valem também as condições dela. Está na seção 9 dos <a href='terminos.html'>Termos</a>." } },

    { id: "cancelar",
      q: { es: "¿Cómo cancelo la renovación?",
           en: "How do I cancel the renewal?",
           pt: "Como cancelo a renovação?" },
      k: { es: "cancelar renovacion suscripcion baja dar de baja no renovar dejar de pagar",
           en: "cancel renewal subscription unsubscribe stop paying",
           pt: "cancelar renovacao assinatura parar de pagar" },
      r: { es: "Desde <a href='https://electronart.pythonanywhere.com/account'>tu cuenta</a>, en la suscripción, botón de cancelar. La licencia sigue andando hasta la fecha que ya pagaste; después no se renueva.",
           en: "From <a href='https://electronart.pythonanywhere.com/account'>your account</a>, on the subscription, cancel button. The licence keeps working until the date you already paid for; after that it does not renew.",
           pt: "Na <a href='https://electronart.pythonanywhere.com/account'>sua conta</a>, na assinatura, botão de cancelar. A licença continua funcionando até a data que você já pagou; depois não se renova." } },

    { id: "offline",
      q: { es: "¿Necesita internet para funcionar?",
           en: "Does it need internet to work?",
           pt: "Precisa de internet para funcionar?" },
      k: { es: "internet conexion offline sin internet nube online desconectado servidor",
           en: "internet connection offline without internet cloud online server",
           pt: "internet conexao offline sem internet nuvem online servidor" },
      r: { es: "No. Todo el diseño —esquemático, simulación, ruteo, DRC, 3D y salida de fabricación— corre en tu máquina, sin cuenta ni nube. Internet hace falta una sola vez, para activar la licencia, y después para lo que es online por naturaleza: stock de LCSC, importar de EasyEDA o el aviso de versión nueva.",
           en: "No. All the design work — schematic, simulation, routing, DRC, 3D and fabrication output — runs on your machine, with no account and no cloud. You need internet once, to activate the licence, and then only for what is online by nature: LCSC stock, importing from EasyEDA or the new-version notice.",
           pt: "Não. Todo o projeto — esquemático, simulação, roteamento, DRC, 3D e saída de fabricação — roda na sua máquina, sem conta e sem nuvem. A internet é necessária uma vez, para ativar a licença, e depois só para o que é online por natureza: estoque da LCSC, importar do EasyEDA ou o aviso de versão nova." } },

    { id: "otra-pc",
      q: { es: "¿Puedo usarla en otra computadora?",
           en: "Can I use it on another computer?",
           pt: "Posso usar em outro computador?" },
      k: { es: "otra otro segunda segundo cambiar cambio maquina reinstalar reinstalo formatear formateo trabajo casa equipos mover trasladar licencia",
           en: "another other second change machine reinstall format work home devices move transfer licence",
           pt: "outro outra segundo segunda trocar maquina reinstalar formatar trabalho casa equipamentos mover transferir licenca" },
      r: { es: "Sí. La licencia comprada va atada a tu correo, no a una máquina: instalás en la otra computadora y activás con el mismo correo. Si formateás o reinstalás, es el mismo paso. (La licencia de <i>prueba</i> sí queda atada al equipo donde la pediste.)",
           en: "Yes. A purchased licence is tied to your email, not to a machine: install on the other computer and activate with the same email. If you format or reinstall, it is the same step. (The <i>trial</i> licence is tied to the machine you requested it on.)",
           pt: "Sim. A licença comprada está vinculada ao seu e-mail, não a uma máquina: instale no outro computador e ative com o mesmo e-mail. Se formatar ou reinstalar, é o mesmo passo. (A licença de <i>teste</i> fica vinculada ao equipamento onde você a pediu.)" } },

    { id: "gratuita-comercial",
      q: { es: "¿Puedo vender lo que diseño con la versión gratuita?",
           en: "Can I sell what I design with the free version?",
           pt: "Posso vender o que projeto com a versão gratuita?" },
      k: { es: "comercial vender uso comercial trabajo cliente empresa gratuita marca de agua regalias derechos diseños mios",
           en: "commercial sell commercial use work client company free watermark royalties rights my designs",
           pt: "comercial vender uso comercial trabalho cliente empresa gratuita marca dagua royalties direitos meus projetos" },
      r: { es: "Los diseños son <b>100 % tuyos</b> en cualquier plan, sin regalías ni atribución. Pero la <b>Gratuita y la de Estudiante son para uso personal y educativo</b>: para trabajo comercial necesitás Pro o Industrial. Además la gratuita sale con marca de agua.",
           en: "The designs are <b>100 % yours</b> on any plan, with no royalties and no attribution. But the <b>Free and Student editions are for personal and educational use</b>: for commercial work you need Pro or Industrial. The free edition also adds a watermark.",
           pt: "Os projetos são <b>100 % seus</b> em qualquer plano, sem royalties nem atribuição. Mas as edições <b>Gratuita e Estudante são para uso pessoal e educacional</b>: para trabalho comercial você precisa de Pro ou Industrial. A gratuita também sai com marca d'água." } },

    { id: "que-hace-gratis",
      q: { es: "¿Qué puedo hacer con la versión gratuita?",
           en: "What can I do with the free version?",
           pt: "O que posso fazer com a versão gratuita?" },
      k: { es: "que hace la gratuita que incluye limitaciones capas diferencias entre planes que trae version libre",
           en: "what does the free version do what is included limitations layers differences between plans",
           pt: "o que faz a gratuita o que inclui limitacoes camadas diferencas entre planos" },
      r: { es: "Un diseño completo de dos caras, de punta a punta: esquemático, simulación SPICE, ruteo a mano o automático, DRC y ERC, vista 3D y exportación de Gerber, Excellon y BOM para mandar a fabricar. Lo que queda para los planes pagos es más de dos capas, pares diferenciales, Monte Carlo y FFT, las salidas IPC-2581/ODB++/STEP y el módulo eléctrico industrial.",
           en: "A complete two-layer design, end to end: schematic, SPICE simulation, manual or automatic routing, DRC and ERC, 3D view and Gerber, Excellon and BOM export ready for the fab. What is left for the paid plans is more than two layers, differential pairs, Monte Carlo and FFT, the IPC-2581/ODB++/STEP outputs and the industrial electrical module.",
           pt: "Um projeto completo de duas faces, de ponta a ponta: esquemático, simulação SPICE, roteamento manual ou automático, DRC e ERC, vista 3D e exportação de Gerber, Excellon e BOM para mandar fabricar. O que fica para os planos pagos é mais de duas camadas, pares diferenciais, Monte Carlo e FFT, as saídas IPC-2581/ODB++/STEP e o módulo elétrico industrial." } },

    { id: "industrial",
      q: { es: "¿Qué es el módulo eléctrico / Industrial?",
           en: "What is the electrical / Industrial module?",
           pt: "O que é o módulo elétrico / Industrial?" },
      k: { es: "industrial modulo electrico plc ladder tablero contactor iec 60617 motor mando potencia riel din automatizacion",
           en: "industrial electrical module plc ladder panel contactor iec 60617 motor control power din rail automation",
           pt: "industrial modulo eletrico clp ladder painel contator iec 60617 motor comando potencia trilho din automacao" },
      r: { es: "Es la parte que un EDA de electrónica no hace: esquemas de mando y potencia con simbología IEC 60617 (contactores, guardamotores, térmicos, diferenciales, temporizadores, borneras), el montaje del tablero sobre riel DIN y la <b>simulación del esquema</b> — apretás el pulsador en pantalla y el contactor engancha. Incluye el editor Ladder. Está en Industrial, y también en Estudiante para uso no comercial.",
           en: "It is the part an electronics EDA does not do: control and power diagrams with IEC 60617 symbols (contactors, motor protectors, thermal relays, RCDs, timers, terminal blocks), DIN-rail panel layout and <b>simulation of the diagram</b> — you press the pushbutton on screen and the contactor pulls in. It includes the Ladder editor. It is in Industrial, and also in Student for non-commercial use.",
           pt: "É a parte que um EDA de eletrônica não faz: diagramas de comando e potência com simbologia IEC 60617 (contatores, disjuntores-motor, relés térmicos, DRs, temporizadores, bornes), a montagem do painel em trilho DIN e a <b>simulação do diagrama</b> — você aperta o botão na tela e o contator liga. Inclui o editor Ladder. Está no Industrial, e também no Estudante para uso não comercial." } },

    { id: "fabricacion",
      q: { es: "¿Sirve para fabricar en JLCPCB o PCBWay?",
           en: "Does it work for JLCPCB or PCBWay?",
           pt: "Serve para fabricar na JLCPCB ou PCBWay?" },
      k: { es: "fabricar fabricacion gerber excellon taladro pick and place bom jlcpcb pcbway fabrica exportar archivos",
           en: "manufacture fabrication gerber excellon drill pick and place bom jlcpcb pcbway fab export files",
           pt: "fabricar fabricacao gerber excellon furacao pick and place bom jlcpcb pcbway fabrica exportar arquivos" },
      r: { es: "Sí. Exporta Gerber RS-274X, taladros Excellon, Pick&amp;Place y BOM, que es lo que piden las fábricas más comunes. Los planes pagos suman IPC-2581, ODB++ y STEP.",
           en: "Yes. It exports Gerber RS-274X, Excellon drills, Pick&amp;Place and BOM, which is what the most common fabs ask for. The paid plans add IPC-2581, ODB++ and STEP.",
           pt: "Sim. Exporta Gerber RS-274X, furação Excellon, Pick&amp;Place e BOM, que é o que as fábricas mais comuns pedem. Os planos pagos somam IPC-2581, ODB++ e STEP." } },

    { id: "archivos",
      q: { es: "¿Dónde quedan mis archivos y mi configuración?",
           en: "Where are my files and settings kept?",
           pt: "Onde ficam os meus arquivos e configurações?" },
      k: { es: "donde quedan archivos configuracion preferencias biblioteca carpeta datos respaldo backup circuitron",
           en: "where are files settings preferences library folder data backup circuitron",
           pt: "onde ficam arquivos configuracoes preferencias biblioteca pasta dados backup circuitron" },
      r: { es: "Tus diseños quedan donde vos los guardes, en archivos <code>.ea</code> de tu disco (formato abierto, nada de nube). Tu biblioteca de componentes, footprints, plugins y modelos 3D viven en <code>%USERPROFILE%\\.circuitron</code>, y las preferencias y la licencia en el registro de Windows — todo <b>fuera</b> de la carpeta del programa, así que desinstalar no los toca.",
           en: "Your designs stay wherever you save them, in <code>.ea</code> files on your disk (open format, no cloud). Your component library, footprints, plugins and 3D models live in <code>%USERPROFILE%\\.circuitron</code>, and the preferences and licence in the Windows registry — all <b>outside</b> the program folder, so uninstalling does not touch them.",
           pt: "Seus projetos ficam onde você salvar, em arquivos <code>.ea</code> no seu disco (formato aberto, sem nuvem). Sua biblioteca de componentes, footprints, plugins e modelos 3D ficam em <code>%USERPROFILE%\\.circuitron</code>, e as preferências e a licença no registro do Windows — tudo <b>fora</b> da pasta do programa, então desinstalar não mexe neles." } },

    { id: "problema",
      q: { es: "Algo no funciona, ¿cómo lo reporto?",
           en: "Something is broken, how do I report it?",
           pt: "Algo não funciona, como reporto?" },
      k: { es: "error problema bug falla se cierra se cuelga crash no abre pantalla negra 3d reportar diagnostico ayuda soporte",
           en: "error problem bug crash freezes does not open black screen 3d report diagnostics help support",
           pt: "erro problema bug falha trava nao abre tela preta 3d reportar diagnostico ajuda suporte" },
      r: { es: "Desde el programa: <b>Ayuda ▸ Diagnóstico…</b> arma un informe con tu versión, tu sistema, tu placa de video y el estado de la licencia, y lo copiás o lo mandás con un botón. <b>No incluye tu licencia, tu correo ni tu nombre de usuario.</b> Para contar el problema con tus palabras, <b>Ayuda ▸ Reportar un problema…</b> abre un hilo en el foro.",
           en: "From the program: <b>Help ▸ Diagnostics…</b> builds a report with your version, your system, your graphics card and the state of your licence, and you copy it or send it with one button. <b>It does not include your licence, your email or your username.</b> To describe the problem in your own words, <b>Help ▸ Report a problem…</b> opens a forum thread.",
           pt: "No programa: <b>Ajuda ▸ Diagnóstico…</b> monta um relatório com a sua versão, o seu sistema, a sua placa de vídeo e o estado da licença, e você copia ou envia com um botão. <b>Não inclui a sua licença, o seu e-mail nem o seu nome de usuário.</b> Para contar o problema com as suas palavras, <b>Ajuda ▸ Reportar um problema…</b> abre um tópico no fórum." } },

    { id: "docente",
      q: { es: "¿Puedo usarlo para dar clases?",
           en: "Can I use it to teach?", pt: "Posso usar para dar aulas?" },
      k: { es: "clases curso docente profesor escuela instituto laboratorio aula enseñar capacitacion",
           en: "classes course teacher professor school institute lab classroom teach training",
           pt: "aulas curso docente professor escola instituto laboratorio sala ensinar treinamento" },
      r: { es: "Las instituciones educativas pueden usar Student en aulas y laboratorios sin cargo. Para cursos pagos que se apoyan en el software corresponde una licencia por docente: Pro si el curso es de electrónica y PCB, e Industrial si se apoya en el módulo eléctrico/PLC.",
           en: "Educational institutions can use Student in classrooms and labs at no cost. For paid courses that rely on the software, a per-teacher licence applies: Pro if the course is about electronics and PCB, Industrial if it relies on the electrical/PLC module.",
           pt: "Instituições educacionais podem usar o Student em salas e laboratórios sem custo. Para cursos pagos que se apoiam no software, corresponde uma licença por docente: Pro se o curso é de eletrônica e PCB, e Industrial se se apoia no módulo elétrico/CLP." } },

    { id: "contacto",
      q: { es: "Quiero hablar con una persona",
           en: "I want to talk to a person", pt: "Quero falar com uma pessoa" },
      k: { es: "contacto contactar hablar persona humano soporte ayuda mail correo escribir telefono whatsapp",
           en: "contact talk person human support help mail email write phone whatsapp",
           pt: "contato falar pessoa humano suporte ajuda mail e-mail escrever telefone whatsapp" },
      r: { es: "Por correo a <a href='mailto:" + CORREO + "'>" + CORREO + "</a>, o en el <a href='" + FORO + "'>foro</a>, donde además queda para el que tenga la misma duda después.",
           en: "By email at <a href='mailto:" + CORREO + "'>" + CORREO + "</a>, or on the <a href='" + FORO + "'>forum</a>, where it also stays for the next person with the same question.",
           pt: "Por e-mail em <a href='mailto:" + CORREO + "'>" + CORREO + "</a>, ou no <a href='" + FORO + "'>fórum</a>, onde também fica para quem tiver a mesma dúvida depois." } }
  ];

  /* ── Búsqueda ────────────────────────────────────────────────────────────
     Sin red y sin modelo: puntaje por palabras. Lo único que importa resolver
     bien son los sinónimos, y para eso está la lista `k` de cada entrada. */

  function normalizar(s) {
    return (s || "").toLowerCase()
      .normalize("NFD").replace(/[̀-ͯ]/g, "")   // saca acentos
      .replace(/[^a-z0-9ñ\s]/g, " ")
      .replace(/\s+/g, " ").trim();
  }

  /* Palabras que aparecen en cualquier pregunta y no distinguen nada. Sin
     esto, «¿cómo hago para…?» le suma puntos a media base. */
  var VACIAS = normalizar(
    "que como cual cuales donde cuando por para con sin del las los una uno " +
    "the how what where when for with and you your can i do does is are my " +
    "de la el en un es se me mi te su al lo y o a of to it on " +
    "o que como onde quando por para com sem do da os as um uma e"
  ).split(" ");

  function palabras(texto) {
    var fuera = [], t = normalizar(texto).split(" ");
    for (var i = 0; i < t.length; i++) {
      if (t[i].length >= 3 && VACIAS.indexOf(t[i]) < 0) fuera.push(t[i]);
    }
    return fuera;
  }

  /* Raíz aproximada: se van cortando letras del final mientras quede algo de
     cinco o más. Es lo que hace que «contactores» encuentre «contactor»,
     «instalación» encuentre «instalar» y «licencias» encuentre «licencia»
     sin meterle un lematizador de verdad a una página estática. */
  function raizEn(palabra, texto) {
    for (var n = palabra.length; n >= 5; n--) {
      if (texto.indexOf(palabra.slice(0, n)) >= 0) return true;
    }
    return false;
  }

  function puntaje(consulta, entrada, lang) {
    var p = palabras(consulta);
    if (!p.length) return { s: 0, exactos: 0 };
    var claves = normalizar(entrada.k[lang] || "");
    var pregunta = normalizar(entrada.q[lang] || "");
    var total = 0, exactos = 0;
    for (var i = 0; i < p.length; i++) {
      var w = p[i];
      /* Palabra exacta en las claves: la señal fuerte. La raíz vale la mitad. */
      if (new RegExp("(^| )" + w + "( |$)").test(claves)) { total += 3; exactos++; }
      else if (raizEn(w, claves)) total += 1.5;
      if (pregunta.indexOf(w) >= 0) total += 1;
    }
    /* Se normaliza por la cantidad de palabras de la consulta: si no, una
       pregunta larga le gana siempre a una corta por acumulación. */
    return { s: total / Math.sqrt(p.length), exactos: exactos };
  }

  function buscar(consulta, lang) {
    var puntuadas = BASE.map(function (e) {
      var r = puntaje(consulta, e, lang);
      return { e: e, s: r.s, exactos: r.exactos };
    }).filter(function (x) { return x.s > 0; })
      .sort(function (a, b) { return b.s - a.s; });
    if (!puntuadas.length) return null;
    /* Lo que separa «te contesto» de «no sé». Dos caminos, porque uno solo se
       equivocaba de un lado o del otro: el puntaje normalizado castiga las
       preguntas largas («me sirve para diseñar un tablero con contactores»
       quedaba abajo del umbral aunque «tablero» pegara exacto), y bajarlo a
       secas hacía contestar cualquier cosa. Una palabra distintiva que pegue
       EXACTA en las claves —«plata», «tablero», «gerber», «smartscreen»— es
       señal suficiente por sí sola. */
    if (puntuadas[0].exactos < 1 && puntuadas[0].s < 2.4) return null;
    return puntuadas.slice(0, 4);
  }

  /* ── Interfaz ────────────────────────────────────────────────────────────
     Sistema «Máscara»: chaflán a 45° recortado con clip-path, lámina de
     kapton para el panel (nunca vidrio blanco), pads perforados en la lista
     y el oro usado dos veces por pantalla, no más. */

  var CSS = [
    "#ea-asis,#ea-asis-tab{position:fixed;right:18px;z-index:9999;font-family:var(--f-body,system-ui)}",
    "#ea-asis-tab{bottom:18px;display:flex;align-items:center;gap:.55rem;",
    "  padding:.62rem 1.05rem;cursor:pointer;border:1px solid var(--border-2,#3a404f);",
    "  background:var(--surface,#1b1e25);color:var(--text,#e7e4dc);",
    "  font-family:var(--f-title,sans-serif);font-size:.86rem;letter-spacing:.10em;",
    "  text-transform:uppercase;box-shadow:0 10px 26px rgba(0,0,0,.45);",
    "  clip-path:polygon(11px 0,100% 0,100% calc(100% - 11px),calc(100% - 11px) 100%,0 100%,0 11px)}",
    "#ea-asis-tab:hover{border-color:var(--gold,#c9a227);color:#fff}",
    "#ea-asis-tab .pad{width:9px;height:9px;border-radius:50%;background:var(--bg,#0c0e12);",
    "  border:3px solid var(--gold,#c9a227);flex:none}",
    "#ea-asis{bottom:18px;width:min(380px,calc(100vw - 36px));max-height:min(560px,calc(100vh - 36px));",
    "  display:none;flex-direction:column;background:color-mix(in srgb,var(--surface,#1b1e25) 92%,transparent);",
    "  backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px);",
    "  border:1px solid var(--border-2,#3a404f);border-top-color:rgba(233,198,75,.28);",
    "  box-shadow:0 22px 54px rgba(0,0,0,.55);color:var(--text,#e7e4dc);",
    "  clip-path:polygon(14px 0,100% 0,100% calc(100% - 14px),calc(100% - 14px) 100%,0 100%,0 14px)}",
    "#ea-asis.abierto{display:flex}",
    "#ea-asis header{display:flex;align-items:center;gap:.6rem;padding:.95rem 1.1rem .75rem;",
    "  border-bottom:1px solid var(--border,#2c313d)}",
    "#ea-asis header .t{font-family:var(--f-title,sans-serif);font-size:.95rem;letter-spacing:.06em}",
    "#ea-asis header .s{font-family:var(--f-data,monospace);font-size:.62rem;letter-spacing:.18em;",
    "  text-transform:uppercase;color:var(--muted-2,#62666f)}",
    "#ea-asis header button{margin-left:auto;background:none;border:0;color:var(--muted,#9a9da6);",
    "  cursor:pointer;font-size:1.15rem;line-height:1;padding:.1rem .3rem}",
    "#ea-asis header button:hover{color:var(--gold-hi,#e9c64b)}",
    "#ea-asis .cuerpo{overflow-y:auto;padding:.9rem 1.1rem;font-size:.9rem;line-height:1.62;",
    "  color:var(--muted,#9a9da6);flex:1}",
    "#ea-asis .cuerpo b,#ea-asis .cuerpo strong{color:var(--text,#e7e4dc);font-weight:600}",
    "#ea-asis .cuerpo a{color:var(--gold,#c9a227)}",
    "#ea-asis .cuerpo code{font-family:var(--f-data,monospace);font-size:.84em;",
    "  background:var(--bg-2,#14161b);border:1px solid var(--border,#2c313d);padding:.05rem .3rem}",
    "#ea-asis .rot{font-family:var(--f-data,monospace);font-size:.6rem;letter-spacing:.2em;",
    "  text-transform:uppercase;color:var(--muted-2,#62666f);margin:1.1rem 0 .5rem}",
    "#ea-asis .sug{display:grid;gap:.35rem;list-style:none;padding:0;margin:0}",
    "#ea-asis .sug button{display:flex;gap:.6rem;align-items:flex-start;width:100%;text-align:left;",
    "  background:none;border:0;color:var(--muted,#9a9da6);cursor:pointer;padding:.25rem 0;",
    "  font:inherit;font-size:.86rem;line-height:1.45}",
    "#ea-asis .sug button::before{content:'';flex:none;width:9px;height:9px;margin-top:.42rem;",
    "  border-radius:50%;background:var(--bg,#0c0e12);border:3px solid var(--gold-lo,#7a6417)}",
    "#ea-asis .sug button:hover{color:var(--text,#e7e4dc)}",
    "#ea-asis .sug button:hover::before{border-color:var(--gold,#c9a227)}",
    "#ea-asis .yo{color:var(--text,#e7e4dc);font-family:var(--f-data,monospace);font-size:.8rem;",
    "  border-left:2px solid var(--copper,#b87333);padding-left:.7rem;margin:1.2rem 0 .7rem}",
    "#ea-asis form{display:flex;gap:.5rem;padding:.7rem 1.1rem;border-top:1px solid var(--border,#2c313d)}",
    "#ea-asis input{flex:1;min-width:0;background:var(--bg,#0c0e12);color:var(--text,#e7e4dc);",
    "  border:1px solid var(--border,#2c313d);padding:.5rem .65rem;font:inherit;font-size:.86rem}",
    "#ea-asis input:focus{outline:2px solid var(--gold,#c9a227);outline-offset:2px;border-color:transparent}",
    "#ea-asis form button{background:var(--surface-2,#242832);color:var(--text,#e7e4dc);cursor:pointer;",
    "  border:1px solid var(--border-2,#3a404f);padding:.5rem .8rem;font:inherit;font-size:.8rem;",
    "  clip-path:polygon(8px 0,100% 0,100% calc(100% - 8px),calc(100% - 8px) 100%,0 100%,0 8px)}",
    "#ea-asis form button:hover{border-color:var(--gold,#c9a227)}",
    "#ea-asis .pie{padding:0 1.1rem .8rem;font-family:var(--f-data,monospace);font-size:.6rem;",
    "  line-height:1.5;color:var(--muted-2,#62666f);display:flex;gap:.6rem;justify-content:space-between}",
    "#ea-asis .pie button{background:none;border:0;color:var(--muted-2,#62666f);cursor:pointer;",
    "  font:inherit;text-decoration:underline;padding:0;flex:none}",
    "#ea-asis .pie button:hover{color:var(--muted,#9a9da6)}",
    "@media (prefers-reduced-motion:no-preference){",
    "  #ea-asis .cuerpo>*{animation:ea-asis-in .22s cubic-bezier(.2,.7,.3,1) both}",
    "  @keyframes ea-asis-in{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:none}}}"
  ].join("");

  var caja, cuerpo, entrada, tab, lang = "es";

  function t(clave) { return (UI[lang] || UI.es)[clave]; }

  function crearNodo(html) {
    var d = document.createElement("div");
    d.innerHTML = html;
    return d.firstElementChild;
  }

  function pintarSugeridas(titulo, entradas) {
    var rot = document.createElement("p");
    rot.className = "rot";
    rot.textContent = titulo;
    var ul = document.createElement("ul");
    ul.className = "sug";
    entradas.forEach(function (e) {
      var li = document.createElement("li");
      var b = document.createElement("button");
      b.type = "button";
      b.textContent = e.q[lang] || e.q.es;
      b.addEventListener("click", function () { responder(e, e.q[lang] || e.q.es); });
      li.appendChild(b);
      ul.appendChild(li);
    });
    cuerpo.appendChild(rot);
    cuerpo.appendChild(ul);
  }

  function pintarInicio() {
    cuerpo.innerHTML = "";
    var p = document.createElement("p");
    p.textContent = t("saludo");
    cuerpo.appendChild(p);
    pintarSugeridas(t("sugeridas"), BASE.filter(function (e) { return e.dest; }));
    cuerpo.scrollTop = 0;
  }

  function eco(texto) {
    var yo = document.createElement("p");
    yo.className = "yo";
    yo.textContent = texto;
    cuerpo.appendChild(yo);
  }

  function responder(elegida, textoUsuario) {
    eco(textoUsuario);
    var p = document.createElement("div");
    p.innerHTML = elegida.r[lang] || elegida.r.es;
    cuerpo.appendChild(p);
    /* Relacionadas: las dos siguientes por puntaje sobre la pregunta canónica,
       que es la forma barata de sugerir «lo que suele venir después». */
    var cercanas = (buscar(elegida.q[lang] || elegida.q.es, lang) || [])
      .map(function (x) { return x.e; })
      .filter(function (e) { return e.id !== elegida.id; }).slice(0, 2);
    if (cercanas.length) pintarSugeridas(t("relacionadas"), cercanas);
    cuerpo.scrollTop = cuerpo.scrollHeight;
  }

  function preguntar(texto) {
    if (!texto.trim()) return;
    var hallazgos = buscar(texto, lang);
    if (!hallazgos) {
      eco(texto);
      var p = document.createElement("p");
      p.innerHTML = t("nada") + "<br><br>" +
        "<a href='" + FORO + "'>" + t("foro") + "</a> · " +
        "<a href='mailto:" + CORREO + "'>" + t("correo") + "</a>";
      cuerpo.appendChild(p);
      pintarSugeridas(t("sugeridas"), BASE.filter(function (e) { return e.dest; }));
      cuerpo.scrollTop = cuerpo.scrollHeight;
      return;
    }
    responder(hallazgos[0].e, texto);
  }

  function traducirCascara() {
    if (!caja) return;
    tab.querySelector("span.txt").textContent = t("abrir");
    tab.setAttribute("aria-label", t("abrir"));
    caja.querySelector("header .t").textContent = t("titulo");
    caja.querySelector("header .s").textContent = t("subtitulo");
    caja.querySelector("header button").setAttribute("aria-label", t("cerrar"));
    entrada.placeholder = t("escribi");
    caja.querySelector("form button").textContent = t("enviar");
    caja.querySelector(".pie .nota").textContent = t("pie");
    caja.querySelector(".pie button").textContent = t("ocultar");
  }

  function abrir(si) {
    caja.classList.toggle("abierto", si);
    tab.style.display = si ? "none" : "flex";
    if (si) entrada.focus();
  }

  function construir() {
    var estilo = document.createElement("style");
    estilo.textContent = CSS;
    document.head.appendChild(estilo);

    tab = crearNodo("<button id='ea-asis-tab' type='button'>" +
                    "<span class='pad'></span><span class='txt'></span></button>");
    caja = crearNodo(
      "<aside id='ea-asis' role='dialog' aria-live='polite'>" +
      "<header><div><div class='t'></div><div class='s'></div></div>" +
      "<button type='button'>✕</button></header>" +
      "<div class='cuerpo'></div>" +
      "<form><input type='text' autocomplete='off'><button type='submit'></button></form>" +
      "<div class='pie'><span class='nota'></span><button type='button'></button></div>" +
      "</aside>");
    document.body.appendChild(tab);
    document.body.appendChild(caja);

    cuerpo = caja.querySelector(".cuerpo");
    entrada = caja.querySelector("input");

    tab.addEventListener("click", function () { abrir(true); });
    caja.querySelector("header button").addEventListener("click", function () {
      abrir(false);
    });
    caja.querySelector("form").addEventListener("submit", function (ev) {
      ev.preventDefault();
      preguntar(entrada.value);
      entrada.value = "";
    });
    /* «Ocultar»: se va del todo y no vuelve hasta que se limpie el navegador.
       Un asistente que no se puede sacar de la pantalla es publicidad. */
    caja.querySelector(".pie button").addEventListener("click", function () {
      try { localStorage.setItem(CLAVE_OCULTO, "1"); } catch (e) {}
      caja.remove();
      tab.remove();
      caja = null;
    });
    document.addEventListener("keydown", function (ev) {
      if (ev.key === "Escape" && caja && caja.classList.contains("abierto")) {
        abrir(false);
      }
    });

    traducirCascara();
    pintarInicio();
  }

  function idiomaActual() {
    var l = (document.documentElement.lang || "es").slice(0, 2).toLowerCase();
    return UI[l] ? l : "es";
  }

  function iniciar() {
    try {
      if (localStorage.getItem(CLAVE_OCULTO) === "1") return;
    } catch (e) {}
    lang = idiomaActual();
    construir();
    /* El selector de idioma lo maneja `i18n.js`, que deja el resultado en el
       atributo `lang` del documento. Observarlo evita que los dos archivos se
       tengan que conocer por dentro. */
    if (window.MutationObserver) {
      new MutationObserver(function () {
        var nuevo = idiomaActual();
        if (nuevo === lang || !caja) return;
        lang = nuevo;
        traducirCascara();
        pintarInicio();
      }).observe(document.documentElement, { attributes: true,
                                             attributeFilter: ["lang"] });
    }
  }

  /* Se construye DESPUÉS de que `i18n.js` capturó la página: así sus nodos no
     entran al diccionario y no se los intenta traducir dos veces. */
  function arrancar() { setTimeout(iniciar, 0); }
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", arrancar);
  } else {
    arrancar();
  }

  window.EA_ASISTENTE = { BASE: BASE, buscar: buscar, normalizar: normalizar };
})();
